// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjncgwwcpqeytwvhutnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbmNnd3djcHFleXR3dmh1dG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzUwODUsImV4cCI6MjA2NTc1MTA4NX0.Dy0AgPwhhiHmHxDu9CoCh8d8sHh3udMWi5Uv8W1cqAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);